### ISSUE TITLE
fails to build with trunk (openssl 1.0.2g changes)

### ISSUE THREAD

**Issue by Andy2244** [el1n/OpenWRT-package-softether#17]
The openssl 1.0.2g changes break softether:
`Network.c:(.text+0xb3d7): undefined reference to 'SSLv3_method'`

`OPENSSL_NO_SSL3_METHOD`
Seems to-be defined by default now and i could not find a option to enable those exports. So instead i did this inside Network.c:
```
if (client_tls == false)
{
#ifndef OPENSSL_NO_SSL3_METHOD
	SSL_CTX_set_ssl_version(ssl_ctx, SSLv3_method());
#endif
```

bye
Andy

**Comment by Alberts00** [comment]
This seems to also affect Chaos Calmer failing the network check when using vpncmd.

> Checking 'Network system'... 
Connect Failed. (0)
              Fail

**Comment by el1n** [comment]
changes are probably like this.
https://github.com/el1n/SoftEtherVPN/commits/issue17

but need to think because the softether still supporting SSLv3.

**Comment by el1n** [comment]
for now, sevpn4wrt is no longer supporting SSLv3 with OpenWrt 15.05 or later version.
