### ISSUE TITLE
Error compile on 14.07 ramips

### ISSUE THREAD

**Issue by lantsing** [el1n/OpenWRT-package-softether#9]
Applying ./patches/200-add-rc-openwrt.patch using plaintext: 
patching file rc/vpnbridge
patching file rc/vpnclient
patching file rc/vpnserver
touch /home/smarthon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/v4.14-9529/.prepared_58477cf31ade2fe0285540c48051813a
rm -f /home/smarthon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/v4.14-9529/.configured_
touch /home/smarthon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/v4.14-9529/.configured_
make -C /home/smarthon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/v4.14-9529 -f src/makefiles/linux_32bit.mak src/bin/BuiltHamcoreFiles/unix/hamcore.se2
make[4]: Entering directory `/home/smarthon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/v4.14-9529'
cc -DNDEBUG -DVPN_SPEED -DUNIX -DUNIX_LINUX -D_REENTRANT -DREENTRANT -D_THREAD_SAFE -D_THREADSAFE -DTHREAD_SAFE -DTHREADSAFE -D_FILE_OFFSET_BITS=64 -I./src/ -I./src/Cedar/ -I./src/Mayaqua/ -O2 -fsigned-char  -c src/Mayaqua/Cfg.c -o tmp/objs/Mayaqua/Cfg.o
In file included from src/Mayaqua/Cfg.c:125:0:
./src/Mayaqua/Mayaqua.h:285:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
make[4]: *** [tmp/objs/Mayaqua/Cfg.o] Error 1
make[4]: Leaving directory `/home/smarthon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/v4.14-9529'
make[3]: *** [/home/smarthon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/v4.14-9529/.built] Error 2
make[3]: Leaving directory `/home/smarthon/openwrt/feeds/SoftetherVpn/softethervpn'
make[2]: *** [package/feeds/SoftetherVpn/softethervpn/compile] Error 2
make[2]: Leaving directory `/home/smarthon/openwrt'
make[1]: *** [/home/smarthon/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/smarthon/openwrt'
make: *** [world] 错误 2
smarthon@Smarthon-PC:~/openwrt$

**Comment by el1n** [comment]
u need install the readline headers.

its not for openwrt.
use package mngr for your distribution.

**Comment by fededim** [comment]
I have the same problem, but I did not understand if
1) the "readline-dev" package should be installed in the host distribution (e.g Debian, Ubuntu, ecc.) or
2) the "readline-dev" package should be installed in the toolchain distribution

From what you said it seems case 1), even though it does not make sense since the include header are taken from openwrt toolchain.

**Comment by Alberts00** [comment]
@fededim 
Readline must be installed in the router and in the host. But if the error is when compiling it is because host distribution lacks it.
```sudo apt-get install -y subversion make gcc g++ libncurses5-dev libghc-zlib-dev libreadline-dev libssl-dev gawk bzip2 patch xz-utils git unzip```

I'm not the creator of the repository, but my guess is that it is done because this allows to compile Softether without having to compile readline every time softether is compiled, it can just use your hosts library. Doubt that the time fixing it would be worth it, but if you want to I can look into it later this month :)

By the way, if you're looking for specific packages I have a daily cronjob which compiles newest packages. http://vpslv.tirlins.com/openwrt/packs/ If you're looking for a specific architecture I can add it.
